# Generated by Django 3.2 on 2024-05-17 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic_record', '0029_academicyear_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='remarks',
        ),
    ]
